---
name: Math-Prime-XS
version: 0.15
author:
  - Steven Schubiger <schubiger@cpan.org>
abstract: Calculate/detect prime numbers with deterministic tests
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  XSLoader: 0
build_requires:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Math::Prime::XS:
    file: lib/Math/Prime/XS.pm
    version: 0.15
generated_by: Module::Build version 0.2703
